version: "3.9"

services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  core-api:
    build:
      context: ./apps/core-api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"

volumes:
  dbdata: {}
