server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:newwork}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:newwork}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:newwork}}
  jpa:
    hibernate:
      ddl-auto: update   # <-- Let Hibernate create/update the schema in dev
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.default_schema: public
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.security: info